var express=require('express');
var globalConf=require('./config');
var loader=require('./loader');
var app=new express();
app.use(express.static("./page/"));
app.post("/editSing",loader.get('/editSing'));
app.get("/getSing",loader.get('/getSing'));
app.get("/queryBlogByPage",loader.get('/queryBlogByPage'));
app.get("/queryBlogCount",loader.get('/queryBlogCount'));
app.post('/insertArticle',loader.get('/insertArticle'));
app.get('/queryBlogById',loader.get('/queryBlogById'));
app.get('/insertComment',loader.get('/insertComment'));
app.get('/randomCode',loader.get('/randomCode'));
app.get('/queryMarkByBlogId',loader.get('/queryMarkByBlogId'));
app.get('/queryCountCommentById',loader.get('/queryCountCommentById'));
app.get('/queryAllBlog',loader.get('/queryAllBlog'));
app.get('/queryAllTags',loader.get('/queryAllTags'));
app.get('/queryHotBlog',loader.get('/queryHotBlog'));
app.get('/queryNewMark',loader.get('/queryNewMark'));
app.get('/queryTagByTagId',loader.get('/queryTagByTagId'));
app.listen(globalConf.port);